# $Header$

IOI_HOME	= 	ioi
IOI_SRC_HOME	=	$(LT_SRC_HOME)/$(IOI_HOME)
IOI_BIN_HOME    =       $(LT_BIN_HOME)/$(IOI_HOME)
IOI_DOC_HOME	=	$(LT_DOC_HOME)/$(IOI_HOME)

# log_udp library (log_udp.h is included for verbosity settings)
LOG_UDP_HOME		= log_udp
LOG_UDP_SRC_HOME	= $(LT_SRC_HOME)/$(LOG_UDP_HOME)
LOG_UDP_CFLAGS		= -I$(LOG_UDP_SRC_HOME)/include

# commandserver
COMMANDSERVER_HOME	= 	commandserver
COMMANDSERVER_SRC_HOME	= 	$(LT_SRC_HOME)/$(COMMANDSERVER_HOME)

#
# $Log$
#
