#!/bin/csh
# $HeadURL$
# ( ./ioi_soak_test > ioi_soak_test_output_20130913.txt ) >& ioi_soak_test_error_20130913.txt
set ioi_address = "ioi_linux"
#set ioi_address = "ltobs9"
set ioi_port = 7373
set exposure_length_list = "1000 2000 5000 10000 30000 60000 120000"
set exposure_count_list = "1 3 5 9"
#if ( -r /home/dev/bin/ioi/test/SendMultrunCommand.class ) then
#	set multrun_dir = /home/dev/bin/ioi/test/
#else if ( -r /icc/bin/ioi/test/SendMultrunCommand.class ) then
#	set multrun_dir = /icc/bin/ioi/test/
#else 
#	echo "Failed to find directory containing SendMultrunCommand.class."
#	exit 1
#endif
set done = 0
set config_count = 0
set multrun_count = 0
set acquire_ramp_count = 0
date -u
echo "Starting test"
while ( ${done} == 0 )
	foreach exposure_count ( ${exposure_count_list} )
		foreach exposure_length ( ${exposure_length_list} )
			date -u
			echo "Sending config command"
			java ngat.ioi.test.SendConfigCommand -address ${ioi_address} -ioiport ${ioi_port} -x 1 -y 1 -filter J 
#-issserverport 7383 -bssserverport 6683
			set config_status = $status
			if( ${config_status} != 0 ) then
				echo "Config ${config_count} failed."
				exit 1
			endif
			@ config_count ++
			date -u
			echo "Sending Multrun command ${exposure_length} ms x ${exposure_count}"
			#cd ${multrun_dir}
			java ngat.ioi.test.SendMultrunCommand -address ${ioi_address} -ioiport ${ioi_port} -exposureLength ${exposure_length} -exposureCount ${exposure_count} 
#-issserverport 7383 -bssserverport 6683
			set multrun_status = $status
			if( ${multrun_status} != 0 ) then
				echo "Multrun ${multrun_count} (${exposure_length} ms x ${exposure_count}) failed."
				exit 1
			endif
			@ multrun_count ++
			@ acquire_ramp_count += ${exposure_count}
			date -u	
			echo "Completed ${config_count} CONFIG commands and ${multrun_count} MULTRUN commands with ${acquire_ramp_count} AcquireRamps (exposures)."
		end
	end
end
