#!/bin/csh
# Test IO:I Linux VM clock synchronisation.
set ntp_server = 0.centos.pool.ntp.org
#set ntp_server = 192.168.1.11
set doy = `/bin/date +"%j"`
set log_file = /icc/log/ioi_clock_test_cron_${doy}.txt
/usr/sbin/ntpdate -d ${ntp_server} >> ${log_file}
