#!/bin/csh
# $Header$
# Version: $Revision$
# By $Author$
# Change the icc into engineering mode - kill all robotic control processes
# Usage:
#	ioi_engineering_mode
# To return to robotic control, reboot the icc.
echo "Switching to engineering mode."
echo "This will only succeed if you are root."
#
# Power down the ASIC
#
java ngat.ioi.command.PowerDownASICCommand ioi1 5000
set java_status = $status
if( ${java_status} != 0 ) then
    echo "Failed to power down ASIC."
    exit 1
endif
#
# Kill any running processes
#
if ( -x /icc/bin/scripts/killhup.csh ) then
    echo "Trying to kill AutoBooter."
    /icc/bin/scripts/killhup.csh AutoBooter
    echo "Trying to kill ngat.ioi.IOI."
    /icc/bin/scripts/killhup.csh ngat.ioi.IOI
    echo "Trying to kill DpRt."
    /icc/bin/scripts/killhup.csh DpRt
    echo "Trying to kill icsd_inet."
    /icc/bin/scripts/killhup.csh icsd_inet
else
    echo "killhup not found:ENGINEERING mode FAILED."
endif
#
# $Log$
#
