#!/bin/csh
# Script for printing out error numbers set in Java source files.
# Searches for lines such as:
#     object.setErrorNum(123);
# and prints:
#     123
# Syntax:
#     ioi_error_num <java source filenames>
# $Header$
if($#argv < 1) then
    echo "ioi_error_num <java source filenames>"
    exit
endif
~dev/bin/scripts/java_error_num.csh $argv |  grep -v Processing | grep -v NO_ERROR | sed "s/IOIConstants.IOI_ERROR_CODE_BASE+//g" | sort -n
#
# $Log$
#
